### ISSUE TITLE
Connecting linkedIn account.

### ISSUE THREAD

**Issue by Fraser-Greenlee** [HackCampus/apply#1]
When I try to add my linkedIn account I first get a 500 error then on reload I get taken to https://hackcampus-apply.herokuapp.com/auth/error#! 
with the message
"Authentication failed. If you tried to connect an account, check that you haven't already started another application with that account."
I've tried retrying and disconnecting linkedIn from HackCampus and trying again but I get the same result every time.
Im pretty sure I've not started an application with another account but Im not certain.

**Comment by lachenmayer** [comment]
I don't think it fixed itself ;) https://github.com/HackCampus/apply/commit/1af8fb1ebc51ccda8ce54fe92d4bc3196d8c7acc
Let me know if you have any further issues!
