### ISSUE TITLE
Connecting to LinkedIn gives HTTP 500

### ISSUE THREAD

**Issue by firemansamm** [HackCampus/apply#19]
Trying to connect a LinkedIn account first takes me to the OAuth page, following which the callback page throws a 500. On refresh, it says takes me to an authentication error, suggesting that the token was consumed but something else failed after - perhaps an issue with passport.js?

**Comment by lachenmayer** [comment]
Apologies that this took so long to get fixed, but I've just fixed it - you can read a detailed summary of the issue here: https://github.com/HackCampus/apply/pull/20 (Linkedin increased the length of their tokens recently...)
Would appreciate it if you could try again :)
