### ISSUE TITLE
Input Text Box disappearing 

### ISSUE THREAD

**Issue by mikeyredtiger22** [HackCampus/apply#2]
The text boxes in Step 3 disappear when I start to type in them. 
I am using the grammarly extension on google chrome.

**Comment by mikeyredtiger22** [comment]
The boxes are still there and I can type but the text and border is white. Only one of the text previews to the right only works.

**Comment by lachenmayer** [comment]
Thanks for letting me know! Do you get any errors in the console?
Does disabling the extension fix the problem?

**Comment by mikeyredtiger22** [comment]
I have experimented with a new account. It seems it is just the Grammarly extension causing the issues! Works fine when disabled. Thanks for getting back.
