### ISSUE TITLE
optional contact email field isn't optional

### ISSUE THREAD

**Issue by armandbancila** [HackCampus/apply#7]
contact email: // optional - only needed if different from your registration email

despite the comment it is not optional, I couldn't submit my application until I completed the field and the orange bar at the bottom wouldn't be filled unless the field was completed

**Comment by ray-kim-12** [comment]
<img width="996" alt="screen shot 2017-02-05 at 13 40 33" src="https://cloud.githubusercontent.com/assets/12093854/22628795/b483d2fa-eba8-11e6-880a-e199c8f137c5.png">

**Comment by armandbancila** [comment]
Yeah. Notice the bar. It's not filled and you can't submit your application.
